app/routes/admin_routes.py
# routes.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, Response, session, abort
from flask_login import login_required, current_user
import pandas as pd
from io import BytesIO

from ..db.db_management import check_superadmin, check_admin, delete_course_by_id, delete_user_by_id, delete_pdf_by_id, delete_university_by_id
from ..utils import allowed_file
from ..llama_index.indexing import create_index
from ..db.models import User, Course, Pdf, ChatEntry , University   
from ..db.db_setup import db
from flask import jsonify

__author__ = "Julia Wenkmann"

admin = Blueprint('admin', __name__)

ADMIN_URL = 'admin.admin_page'
SUPERADMIN_URL = 'admin.superadmin_page'



# Routes
@admin.route('/admin')
@login_required
def admin_page():
    user_id = session.get('user_id')
    check_admin(user_id)
    courses = Course.query.filter_by(user_id=user_id).all()
    pdfs_by_course = {}
    for course in courses:
        pdfs = Pdf.query.filter_by(course_id=course.id).all()
        pdfs_by_course[course.id] = [(pdf.id, pdf.title) for pdf in pdfs]
    return render_template('admin.html', courses=courses, pdfs_by_course=pdfs_by_course)


@admin.route('/superadmin')
@login_required
def superadmin_page():
    user_id = session.get('user_id')
    check_superadmin(user_id)
    universities = University.query.all()
    courses = Course.query.all()
    users = User.query.all()
    return render_template('superadmin.html', universities=universities, courses = courses, users = users)


@admin.route('/add_university', methods=['POST'])
@login_required
def add_university():
    user_id = session.get('user_id')
    check_superadmin(user_id)
    name = request.form.get('university_name')
    if current_user is not None:
        new_university = University(name = name)
        db.session.add(new_university)
        db.session.commit()
    else: print("Not logged in")
    return redirect(url_for(SUPERADMIN_URL))


@admin.route('/delete_university', methods=['POST'])
@login_required
def delete_university():
    user_id = session.get('user_id')
    check_superadmin(user_id)
    university_id = request.form['del_university'] 
    delete_university_by_id(university_id)
    return redirect(url_for(SUPERADMIN_URL))

@admin.route('/add_user', methods=['POST'])
@login_required
def add_user():
    user_id = session.get('user_id')
    check_superadmin(user_id)
    university_id = request.form['university']
    username = request.form.get('user_name')
    password_hash = request.form.get('password')
    new_user = User(username=username, password_hash=password_hash, university_id=university_id)
    db.session.add(new_user)
    db.session.commit()
    return redirect(url_for(SUPERADMIN_URL))


@admin.route('/delete_user', methods=['POST'])
@login_required
def delete_user():
    user_id = session.get('user_id')
    check_superadmin(user_id)
    user_id_to_delete = request.form['del_user'] 
    delete_user_by_id(user_id_to_delete)
    return redirect(url_for(SUPERADMIN_URL))


@admin.route('/add_course', methods=['POST'])
@login_required
def add_course():
    user_id = session.get('user_id')
    check_admin(user_id)
    print(f"User_id: {user_id}")
    user = User.query.get(user_id)
    title = request.form.get('title')
    password_hash = request.form.get('course_password')
    api_key = request.form.get('api_key')
    university_id = user.university_id
    new_course = Course(title=title, university_id=university_id, password_hash=password_hash, api_key=api_key, user_id=user_id)
    db.session.add(new_course)
    db.session.commit()
    return redirect(url_for(ADMIN_URL))


@admin.route('/delete_course', methods=['POST'])
@login_required
def delete_course():
    user_id = session.get('user_id')
    check_admin(user_id)
    course_id = request.form['course_del'] 
    delete_course_by_id(course_id)
    return redirect(url_for(ADMIN_URL))


@admin.route('/upload_pdf', methods=['POST'])
@login_required
def upload_pdf():
    print("Entered upload_pdf function")
    try:
        if 'pdf' not in request.files:
            return redirect(url_for(ADMIN_URL))
        file = request.files['pdf']
        if file.filename == '':
            flash('No selected file', 'danger')
            return redirect(url_for(ADMIN_URL))
        if file and allowed_file(file.filename):
            pdf_data = file.read()
            course_id = request.form['course']  
            pdf_id = Pdf.query.count() + 1
            new_pdf = Pdf(title=file.filename, data=pdf_data, course_id=course_id)
            db.session.add(new_pdf)
            db.session.commit()
            print(f"PDF uploaded successfully for course ID: {course_id}")
            api_key = Course.query.get(course_id).api_key
            new_course = check_new_course(course_id)
            print(f"New course created: {new_course}")
            create_index(course_id, pdf_id, pdf_data, api_key, new_course)
            flash('PDF uploaded successfully', 'success')
            return redirect(url_for(ADMIN_URL))
        else:
            flash('Invalid file type', 'danger')
            return redirect(url_for(ADMIN_URL))
    except Exception as e:
        flash(f'An error occurred: {e}', 'danger')
        return redirect(url_for(ADMIN_URL))


@admin.route('/delete_pdf', methods=['POST'])
@login_required
def delete_pdf():
    user_id = session.get('user_id')
    check_admin(user_id)
    pdf_id = request.form['pdf_del'] 
    delete_pdf_by_id(pdf_id)
    return redirect(url_for(ADMIN_URL))


@admin.route('/get_pdfs/<int:course_id>', methods=['GET'], strict_slashes=False)
@login_required
def get_pdfs(course_id):
    pdfs = Pdf.query.filter_by(course_id=course_id).all()
    pdfs_list = [(pdf.id, pdf.title) for pdf in pdfs]
    return jsonify(pdfs_list)


@admin.route('/course_logging/<int:course_id>')
@login_required
def course_logging(course_id):
    user_id = session.get('user_id')
    check_admin(user_id)
    course = Course.query.get_or_404(course_id)
    # Ensure the current user is the creator of the course
    if course.user_id != current_user.id:
        abort(403)
    # Query for PDFs associated with this course
    pdfs = Pdf.query.filter_by(course_id=course_id).all()
    return render_template('course_chat_entries.html', course=course, pdfs=pdfs)


@admin.route('/download-pdf-entries/<int:pdf_id>')
def download_pdf_entries(pdf_id):
    user_id = session.get('user_id')
    check_admin(user_id)
    try:
        entries_query = ChatEntry.query.filter_by(pdf_id=pdf_id).all()
        # Transform the SQLAlchemy objects into a list of dictionaries
        entries = [
            {
                'page_number': entry.page_number, 
                'question': entry.question, 
                'answer': entry.answer
            } for entry in entries_query
        ]
        df = pd.DataFrame(entries)
        output = BytesIO()
        with pd.ExcelWriter(output, engine='openpyxl') as writer:
            df.to_excel(writer, index=False, sheet_name='PDF Entries')
        # Rewind the buffer
        output.seek(0)
        # Create a response object with the Excel file content
        response = Response(output.getvalue(), mimetype='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
        # Set headers to prompt for download with a specific filename
        response.headers['Content-Disposition'] = f'attachment; filename=entries_{pdf_id}.xlsx'
        return response
    except Exception as e:
        # If anything goes wrong, print the error message and return a 500 response
        print(f"Error generating Excel file: {e}")
        return Response("Error generating Excel file", status=500)
    

########################################################Debugging############################################


@admin.errorhandler(403)
def forbidden(error):
    return render_template('403.html'), 403


def get_pdf_data_from_db(pdf_id):
    pdf = db.session.query(Pdf).filter_by(id=pdf_id).first()
    return pdf.data if pdf else None


def check_new_course(course_id):
    num_pdfs_of_course = Pdf.query.filter_by(course_id=course_id).count()
    if num_pdfs_of_course == 0: 
        new_course = True
    else: 
        new_course = False
    return new_course

app/routes/main_routes.py
from flask import Blueprint, render_template, request, redirect, url_for, session
from flask_login import login_user, logout_user

from ..forms import LoginForm 
from ..db.models import User, Course, University   
from ..db.db_setup import db


__author__ = "Julia Wenkmann"

main = Blueprint('main', __name__)

# Routes
@main.route('/')
def index():
    courses = Course.query.all()  
    return render_template('index.html', courses=courses)

@main.route('/test')
def test():
    return render_template('latex.html')


@main.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        if not username or not password:
            return redirect(url_for('main.register'))
        new_user = User(username=username, password=password)
        db.session.add(new_user)
        db.session.commit()
        return redirect(url_for('main.login'))
    return render_template('register.html')

@main.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and user.password_hash == form.password.data:
            # The login_user function is crucial for handling user session with Flask-Login
            session['user_id'] = user.id
            login_user(user)
            
            #Assuming a super admin check with hardcoded username (not recommended for production)
            if user.id == 1:
                universities = University.query.all()
                courses = Course.query.all()
                users = User.query.all()
                return render_template('superadmin.html', universities = universities, courses = courses, users = users)
            else:
                courses = Course.query.filter_by(user_id=user.id).all()
                return render_template('admin.html', courses=courses)
    return render_template('login.html', form=form)



@main.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.index'))

app/routes/user_routes.py
# routes.py
from flask import Blueprint, render_template, request, flash, jsonify

from ..forms import PasswordForm
from ..llama_index.questioning import ask_pdf, ask_course
from ..db.models import Course, Pdf, ChatEntry
from ..db.db_setup import db
import base64
import json


__author__ = "Julia Wenkmann"

user = Blueprint('user', __name__)

# Routes
@user.route('/course/<int:course_id>', methods=['GET', 'POST'])
def course_details(course_id):
    course = Course.query.get_or_404(course_id)
    form = PasswordForm()
    if form.validate_on_submit():#TODO make that secure
        # Assuming you store hashed passwords in 'password_hash'
        if course.password_hash == form.password.data:
            pdfs = Pdf.query.filter_by(course_id=course_id).all()
            return render_template('course_details.html', course=course, pdfs=pdfs, form=form)
        else:
            flash('Incorrect password. Please try again.', 'danger')
    return render_template('verify_password.html', form=form, course_id=course_id)

@user.route('/pdf/<int:pdf_id>')
def chat_with_pdf(pdf_id):
    pdf = Pdf.query.get_or_404(pdf_id)
    api_key = pdf.course.api_key
    pdf_data_base64 = base64.b64encode(pdf.data).decode('utf-8')
    entries = ChatEntry.query.filter_by(pdf_id=pdf_id).all()
    course_id = pdf.course_id
    return render_template('chat_with_pdf.html', pdf_id=pdf_id, pdf_title = pdf.title, course_id = course_id, pdf_data_base64=pdf_data_base64, entries=entries, api_key=api_key)



@user.route('/coursechat/<int:course_id>')
def chat_with_course(course_id):
    course = Course.query.get_or_404(course_id)
    api_key = course.api_key
    pdfs = Pdf.query.filter_by(course_id=course_id).all()
    
    # Extract PDF data in base64 format for each PDF
    pdf_data_map = {}
    pdf_titles = []
    for pdf in pdfs:
        if pdf.data:
            pdf_data_base64 = base64.b64encode(pdf.data).decode('utf-8')
            pdf_data_map[pdf.id] = pdf_data_base64
            pdf_titles.append((pdf.id, pdf.title))
    pdf_data_json = json.dumps(pdf_data_map)
    return render_template('chat_with_course.html', course_id=course_id, pdf_titles=pdf_titles, pdf_data_json=pdf_data_json, api_key=api_key)



@user.route('/get_answer_from_pdf', methods=['POST'])
def get_answer_from_pdf():
    try: 
        print("Entered routes: get_answer_from_pdf")
        # Extract data from the request
        data = request.get_json()
        question = data.get('question')
        pdf_id = data.get('pdf_id')
        page_number = data.get('page_number')
        api_key = data.get('api_key')
        print(f"Question: {question}")
        print(f"Pdf_Id: {pdf_id}")
        # Get the answer
        answer = ask_pdf(question, pdf_id, api_key)
        if answer:
            new_entry = ChatEntry(question=question, answer=answer, page_number=page_number, pdf_id=pdf_id)
            db.session.add(new_entry)
            db.session.commit()
            print("ChatEntry logged succesfully")
        else: 
            print("No answer found")    
        return jsonify({'answer': answer})
    except Exception as e:
        print(f"Error in routes: get_answer: {e}")



@user.route('/get_answer_from_course', methods=['POST'])
def get_answer_from_course():
    try: 
        print("Entered routes: get_answer_from_course")
        # Extract data from the request
        data = request.get_json()
        question = data.get('question')
        course_id = data.get('course_id')
        pdf_id = data.get('pdf_id')
        page_number = data.get('page_number')
        api_key = data.get('api_key')
        print(f"Question: {question}")
        print(f"Course_Id: {pdf_id}")
        print(f"Pdf_Id: {pdf_id}")
        # Get the answer
        answer = ask_course(question, course_id, api_key)
        if answer:
            new_entry = ChatEntry(question=question, answer=answer, page_number=page_number, pdf_id=pdf_id)
            db.session.add(new_entry)
            db.session.commit()
            print("ChatEntry logged succesfully")
        else: 
            print("No answer found")    
        return jsonify({'answer': answer})
    except Exception as e:
        print(f"Error in routes: get_answer: {e}")


def get_static_answer():
    test = "x^2"

    return test



@user.route('/log_chat_entry', methods=['POST'])
def log_chat_entry():
    # Get the data from the request
    data = request.get_json()
    question = data.get('question')
    answer = data.get('answer')
    page_number = data.get('page_number')
    pdf_id = data.get('pdf_id')
    # Create a new ChatEntry instance
    chat_entry = ChatEntry(
        question=question,
        answer=answer,
        page_number=page_number,
        pdf_id=pdf_id
    )
    db.session.add(chat_entry)
    db.session.commit()
    return jsonify({'status': 'success', 'message': 'Chat entry logged successfully'}),  200


########################################################Debugging############################################

@user.errorhandler(403)
def forbidden(error):
    return render_template('403.html'), 403


def get_pdf_data_from_db(pdf_id):
    pdf = db.session.query(Pdf).filter_by(id=pdf_id).first()
    return pdf.data if pdf else None

app/templates/admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
    <title>Admin Page</title>
    <link rel="icon" href="/static/images/favicon.ico">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <!-- Bootstrap JS and jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{{ url_for('main.logout') }}">Instructor Page</a>
        <div class="navbar-nav ml-auto">
            <a class="nav-item nav-link" href="{{ url_for('main.logout') }}">Logout</a>
        </div>
    </nav>

    <div class="container mt-5">
        <div class="row">
            <div class="col-12">
                <h3>Your Courses</h3>
                <div class="list-group">
                    {% for course in courses %}
                    <a href="{{ url_for('admin.course_logging', course_id=course.id) }}" class="list-group-item list-group-item-action">
                        {{ course.title }}
                    </a>                    
                    {% else %}
                        <p>No courses found.</p>
                    {% endfor %}
                </div>
                <hr>
            </div>
        </div>

        <h2 class="mb-4">Add a Course</h2>
        <form action="{{ url_for('admin.add_course') }}" method="post">
            <div class="form-group">
                <label for="title">Course Title</label>
                <input type="text" class="form-control" id="title" name="title" required>
                <br/>
                <label for="api_key">API Key:</label>
                <input type="text" id="api_key" name="api_key" required>
                <label for="course_password">Password:</label>
                <input type="password" id="course_password" name="course_password" required>
            </div>
            <button type="submit" class="btn btn-primary">Add Course</button>
        </form>
        <br/>
        <h2 class="mt-4">Upload PDF to Course</h2>
        <form action="{{ url_for('admin.upload_pdf') }}" method="post" enctype="multipart/form-data">
            <div class="form-group">
                <label for="course">Select a Course</label>
                <select class="form-control" id="course" name="course">
                    {% for course in courses %}
                        <option value="{{ course.id }}">{{ course.title }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="pdf">Choose a PDF file</label>
                <input type="file" class="form-control-file" id="pdf" name="pdf" required>
            </div>
            <button type="submit" class="btn btn-primary">Upload PDF</button>
        </form>
        <br/>
        <h2 class="mt-4">Delete a Course</h2>
        <form action="{{ url_for('admin.delete_course') }}" method="post">
            <div class="form-group">
                <label for="course_del">Select a Course</label>
                <select class="form-control" id="course_del" name="course_del">
                    {% for course in courses %}
                        <option value="{{ course.id }}">{{ course.title }}</option>
                    {% endfor %}
                </select>
            </div>
            <button type="submit" class="btn btn-danger">Delete Course</button>
        </form>

        <h2 class="mt-4">Delete a Pdf</h2>
        <form action="{{ url_for('admin.delete_pdf') }}" method="post">
            <div class="form-group">
                <label for="pdf_course_del">Select a Course</label>
                <select class="form-control" id="pdf_course_del" name="pdf_course_del" title="Select a Course" onchange="updatePdfDropdown(this.value)">
                    {% for course in courses %}
                        <option value="{{ course.id }}">{{ course.title }}</option>
                    {% endfor %}
                </select>
                <br/>
                <select class="form-control" id="pdf_del" name="pdf_del" title="Select a PDF">
                    <!-- Options will be populated dynamically -->
                </select>                
            </div>
            <button type="submit" class="btn btn-danger">Delete Pdf</button>
        </form>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
    function updatePdfDropdown(courseId) {
        console.log("Enreded updatePdfDropdown with courseId: ", courseId);
        $.ajax({
            url: '/get_pdfs/' + courseId,
            method: 'GET',
            dataType: 'json',
            success: function(response) {
                var pdfDropdown = $('#pdf_del');
                pdfDropdown.empty(); // Clear existing options
                $.each(response, function(index, pdf) {
                    pdfDropdown.append($('<option>', {
                        value: pdf[0],
                        text: pdf[1]
                    }));
                });
            },
            error: function(xhr, status, error) {
                console.log("Error: " + status + " " + error);
                console.log(xhr.responseText);
            }
        });
    }

    updatePdfDropdown($('#pdf_course_del').val());
    </script>
    
</body>
</html>

app/templates/course_chat_entries.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ course.title }} -- Overview</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="/static/images/favicon.ico">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <!-- Bootstrap JS and jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{{ url_for('main.logout') }}">CourseChat</a>
        <div class="navbar-nav ml-auto">
            <a class="nav-item nav-link" href="{{ url_for('admin.admin_page') }}">Back</a>
        </div>
    </nav>
    </br>
    <div class="container mt-5">
        <h2 class="mb-4">{{ course.title }} -- Overview</h2>
        <p>Here you can explore questions and answers related to each document.</p>
        <div class="accordion" id="pdfAccordion">
            {% for pdf in pdfs %}
            <div class="card">
                <div class="card-header" id="heading{{ loop.index }}">
                    <h2 class="mb-0">
                        <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#collapse{{ loop.index }}" aria-expanded="true" aria-controls="collapse{{ loop.index }}">
                            {{ pdf.title }}
                        </button>
                    </h2>
                </div>

                <div id="collapse{{ loop.index }}" class="collapse" aria-labelledby="heading{{ loop.index }}" data-parent="#pdfAccordion">
                    <div class="card-body">
                        {% if pdf.entries|length > 0 %}
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Page Number</th>
                                    <th>Question</th>
                                    <th>Answer</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for entry in pdf.entries %}
                                <tr>
                                    <td>{{ entry.page_number }}</td>
                                    <td>{{ entry.question }}</td>
                                    <td>{{ entry.answer | default('Awaiting response', true) }}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        <a href="/download-pdf-entries/{{ pdf.id }}" class="btn btn-primary">Download as Excel</a>
                        {% else %}
                        <p>No chat entries found for this PDF.</p>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% else %}
            <p>No PDFs found for this course.</p>
            {% endfor %}
        </div>
    </div>
    <!-- Bootstrap Bundle with Popper -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
</body>
</html>

app/templates/course_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ course.title }} - Course Details</title>
    <link rel="icon" href="/static/images/favicon.ico">
    <link rel="stylesheet" href="../static/css/course.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <!-- Bootstrap JS and jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{{ url_for('main.logout') }}">CourseChat</a>
        <div class="navbar-nav ml-auto">
            <a class="nav-item nav-link" href="{{ url_for('main.logout') }}">Back</a>
        </div>
    </nav>
    </br>
    <div class="container mt-5">

    <h1>{{ course.title }}</h1>
    </br>
    <h2>Available Scripts</h2>
    </br>
    {% if pdfs %}
        <ul class="pdf-list">
            {% for pdf in pdfs %}
                <li class="pdf-item">
                    <a href="{{ url_for('user.chat_with_pdf', pdf_id=pdf.id) }}" class="pdf-link">
                        <img src="{{ url_for('static', filename='images/pdf.png') }}" alt="PDF Icon" class="pdf-icon">
                        {{ pdf.title }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No PDFs available yet.</p>
    {% endif %}
    </br>
    <a class="btn btn-primary" href="{{ url_for('user.chat_with_course', course_id=course.id) }}">Ask questions about the whole course.</a>
    </div>
</body>
</html>

app/templates/latex.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MathJax Test</title>
    <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
    <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
</head>
<body>
    <p>This is an inline equation: \(x^2\)</p>
    <p>This is a block equation: \[x^2\]</p>
</body>
</html>

app/templates/superadmin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
    <title>Admin Page</title>
    <link rel="icon" href="/static/images/favicon.ico">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <!-- Bootstrap JS and jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{{ url_for('main.logout') }}">Admin Page</a>
        <div class="navbar-nav ml-auto">
            <a class="nav-item nav-link" href="{{ url_for('main.logout') }}">Logout</a>
        </div>
    </nav>

    <div class="container mt-5">
        <h2 class="mt-4">Add a User</h2>
        <form action="{{ url_for('admin.add_user') }}" method="post" enctype="multipart/form-data">
            <div class="form-group">
                <label for="university">Select a University</label>
                <select class="form-control" id="university" name="university" title="Select a University">
                    {% for university in universities %}
                        <option value="{{ university.id }}">{{ university.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="user_name">User Name:</label>
                <input type="text" id="user_name" name="user_name" required>
                <label for="password">Password:</label>
                <input type="password" id="password" name="password" required>
            </div>
            <button type="submit" class="btn btn-primary">Add User</button>
        </form>
        <br/>
        <h2 class="mt-4">Delete a User</h2>
        <form action="{{ url_for('admin.delete_user') }}" method="post" enctype="multipart/form-data">
            <div class="form-group">
                <label for="del_user">Select a User</label>
                <select class="form-control" id="del_user" name="del_user">
                    {% for user in users %}
                        <option value="{{ user.id }}">{{ user.username}}</option>
                    {% endfor %}
                </select>
            </div>
            <button type="submit" class="btn btn-danger">Delete User</button>
        </form>
        <br/>
        <br/>
        <h2 class="mb-4">Add a University</h2>
        <form action="{{ url_for('admin.add_university') }}" method="post">
            <div class="form-group">
                <label for="university_name">University Name:</label>
                <input type="text" class="form-control" id="university_name" name="university_name" required placeholder="Enter university name">
            </div>
            <button type="submit" class="btn btn-primary">Add University</button>
        </form>
        <br/>
        <h2 class="mt-4">Delete a University</h2>
        <form action="{{ url_for('admin.delete_university') }}" method="post" enctype="multipart/form-data">
            <div class="form-group">
                <label for="del_university">Select a University</label>
                <select class="form-control" id="del_university" name="del_university">
                    {% for university in universities %}
                        <option value="{{ university.id }}">{{ university.name}}</option>
                    {% endfor %}
                </select>
            </div>
            <button type="submit" class="btn btn-danger">Delete University</button>
            <p>!!! Use with caution as this will also delete all users, courses, and chatentries associated with that university !!!</p>
        </form>
        </br>
    </div>
    <br/>
    <br/>
</body>
</html>